### ISSUE TITLE
A few minor questions for numbers.ts

### ISSUE THREAD

**Issue by polarker** [alephium/alephium-js#53]
1. Why `alph(1234)` is formated as `1'234`, not `1.234K` since we use `M, B` for 10^6 and 10^9
2. `addApostrophe(1234567)` will be `1234'567` instead of `1'234'567` as far as I see, is this expected?
3. we need tests for `addApostrophe` function or we don't export it

**Comment by polarker** [comment]
4. which one is more understandable for general users: `1'234'567` vs `1.234M`?

**Comment by mvaivre** [comment]
Hey there!
1: this was discussed and agreed [here](https://github.com/alephium/alephium-wallet/issues/116#issuecomment-1016179165).
2, 3: This needs to be tested and fixed, this is not expected.
4. We previously all agreed on using M (link above), but this can be reconsidered if needed. Let's keep in mind that numbers with length >= 6 start to be hard to display in a clean way. We could used the same strategy as in the explorer, use M/B but show the full amount on hover to clear up any potential confusion.

**Comment by polarker** [comment]
Regarding 4: I get the motivation of using `M/B`, but I am afraid that people from non-English region might have issues to understand it.

We could continue with `M/B` until users start to complain about it

**Comment by nop33** [comment]
1. Mika covered this
2. In our discussion that Mika linked above we agreed that the apostrophe would only be added for amounts < 1'000'000, since for anything >= 1'000'000 we use the abbreviation with the letter `M`. I can update the code to cover amounts >= 1'000'000, but it won't be used.
3. I need to add tests, correct.
4. Agreed with everything mentioned above.
